server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: n-t-gateway-server

  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**
        - id:
          uri: lb://
          predicates:
            - Path=
          filters:
            - AuthFilter

