server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**
        - id: ms-pcge
          uri: lb://ms-pcge
          predicates:
            - Path=/pcge/**
        - id: ms-operaciones
          uri: lb://ms-operaciones
          predicates:
            - Path=/operaciones/**, /proveedores/**
        - id: ms-contabilidad
          uri: lb://ms-contabilidad
          predicates:
            - Path=/asientos/**
