server:
  port: 8081
spring:
  application:
    name: n-t-pago

  datasource:
    url: jdbc:mysql://localhost:3306/n_t_pago
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    hostname: localhost