server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: n-t-gateway-server

  cloud:
    gateway:
      routes:
        - id: n-t-auth
          uri: lb://n-t-auth
          predicates:
              - Path=/auth/**
        - id: n-t-pago
          uri: lb://n-t-pago
          predicates:
            - Path=/pago/**
          filters:
            - AuthFilter

